---
abstract: 'Generate URLs to Open Street Map static maps'
author:
  - 'Michael Kröll <pepl@cpan.org>'
build_requires:
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-OSM-StaticMap
provides:
  Geo::OSM::StaticMap:
    file: lib/Geo/OSM/StaticMap.pm
    version: 0.3
requires:
  Geo::Distance: 0
  Math::Trig: 0
  Moose: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Geo-OSM-StaticMap
  homepage: http://github.com/pepl/geo-osm-staticmap/tree
  repository: git://github.com/pepl/geo-osm-staticmap.git
version: 0.3
